spring:
  application:
    name: customer
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:customer
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

server:
  port: 48152

springdoc:
  swagger-ui:
    path: /swagger.html
    enabled: true
